### ISSUE TITLE
[1.18] Arclight crash using the slicer

### ISSUE THREAD

**Issue by muriplz** [PssbleTrngle/SliceAndDice#36] opened 2023-02-22 01:49 UTC
### What happened?

The ponderding of the slicer crashes the client, also placing a slicer makes the clients be on a crash loop if loaded.

I use arclight 1,18! https://github.com/IzzelAliz/Arclight

### Mod Version

1.1.0

### Minecraft Version

1.18

### Forge Version

40.1.80

### Relevant log output

```shell
https://pastebin.com/B3dFcQX8
```

**Comment by PssbleTrngle** [comment] 2023-02-23 19:37
Should be a duplicate of #37

**Closed as completed by PssbleTrngle** 2023-02-23 19:37 UTC
Labels: bug
