### ISSUE TITLE
Make buckets not get consumed in mixing recipes

### ISSUE THREAD

**Issue by TriibuNupsik** [PssbleTrngle/SliceAndDice#167] opened 2024-09-08 14:40 UTC
### Describe the feature you have in mind.

Recipes like the mashed potato one require a milk bucket but then the bucket gets consumed.

Solutions:
1. Make the bucket not get consumed
2. Swap the requirement with milk fluid

### Does this solve a particular problem?

It makes buckets not get consumed in mixing recipes because it's weird when the bucket gets mixed in my food.

**Comment by PssbleTrngle** [comment] 2024-09-19 07:56
This is a duplicate of #108, I will address it there

**Closed as not planned by PssbleTrngle** 2024-09-19 07:56 UTC
Labels: enhancement
