### ISSUE TITLE
Error when trying to join server 

### ISSUE THREAD

**Issue by stann-co** [PssbleTrngle/SliceAndDice#59] opened 2023-05-10 14:42 UTC
### What happened?

Farmers Delight version 1.3.9 - 1.19.X
Create version Create 1.19.2 v0.5.0.i Patch 5

(the time of writing the newest versions)
I get this error when trying to join a server
![image](https://github.com/PssbleTrngle/SliceAndDice/assets/46312671/d65dbc97-c726-431e-88a7-0f334b117532)

### Loader

fabric

### Mod Version

2.1.1

### Minecraft Version

1.19

### Relevant log output

```shell
[20:53:40] [main/INFO]: Loading Minecraft 1.19.2 with Fabric Loader 0.14.19
[20:53:40] [ForkJoinPool-1-worker-9/WARN]: Mod create uses the version 0.5.0.i-1003+1.19.2 which isn't compatible with Loader's extended semantic version format (Could not parse version number component 'i'!), SemVer is recommended for reliably evaluating dependencies and prioritizing newer version
[20:53:40] [ForkJoinPool-1-worker-2/WARN]: Mod flywheel uses the version 0.6.8.a-4 which isn't compatible with Loader's extended semantic version format (Could not parse version number component 'a'!), SemVer is recommended for reliably evaluating dependencies and prioritizing newer version
[20:53:40] [main/WARN]: Warnings were found!
 - Mod 'Create Slice & Dice' (sliceanddice) 2.1.1 recommends any version of farmers-delight, which is missing!
	 - You should install any version of farmers-delight for the optimal experience.
[20:53:40] [main/INFO]: Loading 118 mods:
	- angling 1.0.1
	   |-- cardinal-components-base 5.0.0
	   |-- cardinal-components-entity 5.0.0
	   \-- com_github_llamalad7_mixinextras 0.1.1
	- another_furniture 2.1.2-1.19.2
	- appleskin 2.4.1+mc1.19
	- architectury 6.5.82
	- cloth-config 8.2.88
	   \-- cloth-basic-math 0.6.1
	- clumps 9.0.0+14
	- create 0.5.0.i-1003+1.19.2
	   |-- com_google_code_findbugs_jsr305 3.0.2
	   |-- flywheel 0.6.8.a-4
	   |-- milk 1.0.51
	   |    \-- dripstone_fluid_lib 2.0.1
	   |-- porting_lib 2.1.926+1.19.2
	   |    |-- forge_tags 3.0
	   |    |-- mm 2.3
	   |    |-- porting_lib_accessors 2.1.926+1.19.2
	   |    |-- porting_lib_attributes 2.1.926+1.19.2
	   |    |-- porting_lib_base 2.1.926+1.19.2
	   |    |-- porting_lib_common 2.1.926+1.19.2
	   |    |-- porting_lib_constants 2.1.926+1.19.2
	   |    |-- porting_lib_entity 2.1.926+1.19.2
	   |    |-- porting_lib_extensions 2.1.926+1.19.2
	   |    |-- porting_lib_fake_players 2.1.926+1.19.2
	   |    |-- porting_lib_lazy_registration 2.1.926+1.19.2
	   |    |-- porting_lib_loot 2.1.926+1.19.2
	   |    |-- porting_lib_model_generators 2.1.926+1.19.2
	   |    |-- porting_lib_model_loader 2.1.926+1.19.2
	   |    |-- porting_lib_models 2.1.926+1.19.2
	   |    |-- porting_lib_networking 2.1.926+1.19.2
	   |    |-- porting_lib_obj_loader 2.1.926+1.19.2
	   |    |-- porting_lib_transfer 2.1.926+1.19.2
	   |    \-- serialization_hooks 0.3.26
	   |-- reach-entity-attributes 2.3.0
	   \-- registrate-fabric 1.1.57-MC1.19.2
	- crittersandcompanions 1.19.2-1.0.3
	- emotecraft 2.2.5
	   \-- bendy-lib 2.1.2
	- fabric-api 0.76.0+1.19.2
	   |-- fabric-api-base 0.4.15+8f4e8eb390
	   |-- fabric-api-lookup-api-v1 1.6.14+93d8cb8290
	   |-- fabric-biome-api-v1 9.1.1+16f1e31390
	   |-- fabric-block-api-v1 1.0.2+e415d50e90
	   |-- fabric-blockrenderlayer-v1 1.1.25+cafc6e8e90
	   |-- fabric-client-tags-api-v1 1.0.5+b35fea8390
	   |-- fabric-command-api-v1 1.2.16+f71b366f90
	   |-- fabric-command-api-v2 2.2.1+413cbbc790
	   |-- fabric-commands-v0 0.2.33+df3654b390
	   |-- fabric-containers-v0 0.1.41+df3654b390
	   |-- fabric-content-registries-v0 3.5.2+7c6cd14d90
	   |-- fabric-convention-tags-v1 1.3.0+4bc6e26290
	   |-- fabric-crash-report-info-v1 0.2.8+aeb40ebe90
	   |-- fabric-data-generation-api-v1 5.3.8+413cbbc790
	   |-- fabric-dimensions-v1 2.1.35+0d0f210290
	   |-- fabric-entity-events-v1 1.5.4+9244241690
	   |-- fabric-events-interaction-v0 0.4.34+562bff6e90
	   |-- fabric-events-lifecycle-v0 0.2.36+df3654b390
	   |-- fabric-game-rule-api-v1 1.0.24+b6b6abb490
	   |-- fabric-item-api-v1 1.6.6+b7d1888890
	   |-- fabric-item-groups-v0 0.3.39+9244241690
	   |-- fabric-key-binding-api-v1 1.0.25+5c4fce2890
	   |-- fabric-keybindings-v0 0.2.23+df3654b390
	   |-- fabric-lifecycle-events-v1 2.2.4+1b46dc7890
	   |-- fabric-loot-api-v2 1.1.13+83a8659290
	   |-- fabric-loot-tables-v1 1.1.16+9e7660c690
	   |-- fabric-message-api-v1 5.0.7+93d8cb8290
	   |-- fabric-mining-level-api-v1 2.1.24+33fbc73890
	   |-- fabric-models-v0 0.3.21+c6af733c90
	   |-- fabric-networking-api-v1 1.2.11+10eb22f490
	   |-- fabric-networking-v0 0.3.28+df3654b390
	   |-- fabric-object-builder-api-v1 4.2.2+d8ef690890
	   |-- fabric-particles-v1 1.0.14+4d0d570390
	   |-- fabric-recipe-api-v1 1.0.1+413cbbc790
	   |-- fabric-registry-sync-v0 0.9.32+9244241690
	   |-- fabric-renderer-api-v1 1.2.1+1adbf27790
	   |-- fabric-renderer-indigo 0.8.0+1adbf27790
	   |-- fabric-renderer-registries-v1 3.2.24+df3654b390
	   |-- fabric-rendering-data-attachment-v1 0.3.19+6e0787e690
	   |-- fabric-rendering-fluids-v1 3.0.11+4d0d570390
	   |-- fabric-rendering-v0 1.1.27+df3654b390
	   |-- fabric-rendering-v1 1.12.1+d8ef690890
	   |-- fabric-resource-conditions-api-v1 2.1.2+aae9039d90
	   |-- fabric-resource-loader-v0 0.8.4+edbdcddb90
	   |-- fabric-screen-api-v1 1.0.32+4d0d570390
	   |-- fabric-screen-handler-api-v1 1.3.7+1cc24b1b90
	   |-- fabric-sound-api-v1 1.0.2+c4f28df590
	   |-- fabric-textures-v0 1.0.24+aeb40ebe90
	   |-- fabric-transfer-api-v1 2.1.6+413cbbc790
	   \-- fabric-transitive-access-wideners-v1 1.3.3+08b73de490
	- fabric-language-kotlin 1.9.4+kotlin.1.8.21
	   |-- org_jetbrains_kotlin_kotlin-reflect 1.8.21
	   |-- org_jetbrains_kotlin_kotlin-stdlib 1.8.21
	   |-- org_jetbrains_kotlin_kotlin-stdlib-jdk7 1.8.21
	   |-- org_jetbrains_kotlin_kotlin-stdlib-jdk8 1.8.21
	   |-- org_jetbrains_kotlinx_atomicfu-jvm 0.20.2
	   |-- org_jetbrains_kotlinx_kotlinx-coroutines-core-jvm 1.6.4
	   |-- org_jetbrains_kotlinx_kotlinx-coroutines-jdk8 1.6.4
	   |-- org_jetbrains_kotlinx_kotlinx-datetime-jvm 0.4.0
	   |-- org_jetbrains_kotlinx_kotlinx-serialization-cbor-jvm 1.5.0
	   |-- org_jetbrains_kotlinx_kotlinx-serialization-core-jvm 1.5.0
	   \-- org_jetbrains_kotlinx_kotlinx-serialization-json-jvm 1.5.0
	- fabricloader 0.14.19
	- fallingtree 3.10.0
	- farmersdelight 1.19.2-1.3.9
	- ferritecore 5.0.3
	- geckolib3 3.1.40
	   \-- com_eliotlash_mclib_mclib 20
	- immersive_paintings 0.6.0+1.19.2
	- java 17
	- kubejs 1902.6.0-build.142
	- lazydfu 0.1.3
	- lithium 0.11.1
	- mavapi 1.0.1
	- mavm 1.2.0
	- minecraft 1.19.2
	- moremobvariants 1.0.1
	- naturalist 3.0.2
	- phosphor 0.8.1
	- player-animator 1.0.2
	- rhino 1902.2.2-build.268
	- servercore 1.3.3-1.19.2
	   |-- com_electronwill_night-config_core 3.6.6
	   |-- com_electronwill_night-config_toml 3.6.6
	   |-- fabric-permissions-api-v0 0.2-SNAPSHOT
	   |-- me_lucko_spark-api 0.1-SNAPSHOT
	   \-- placeholder-api 2.0.0-pre.1+1.19.2
	- sliceanddice 2.1.1
	   \-- forgeconfigapiport 4.2.11
	- spark 1.10.37
	- spiderstpo 1.19.2-2.0.3
	- walllanterns 1.4.0-1.19
[20:53:40] [main/INFO]: SpongePowered MIXIN Subsystem Version=0.8.5 Source=file:/C:/Users/jackc/Desktop/stann%20create%20server/libraries/net/fabricmc/sponge-mixin/0.12.4+mixin.0.8.5/sponge-mixin-0.12.4+mixin.0.8.5.jar Service=Knot/Fabric Env=SERVER
[20:53:40] [main/INFO]: Compatibility level set to JAVA_17
[20:53:41] [main/WARN]: Reference map 'immersive_paintings-common-refmap.json' for immersive_paintings.mixin.json could not be read. If this is a development environment you can ignore this message
[20:53:41] [main/INFO]: Loaded configuration file for Lithium: 114 options available, 2 override(s) found
[20:53:41] [main/INFO]: [ServerCore] Loading...
[20:53:41] [main/WARN]: Force-disabling mixin 'alloc.blockstate.StateMixin' as rule 'mixin.alloc.blockstate' (added by mods [ferritecore]) disables it and children
[20:53:41] [main/WARN]: Force-disabling mixin 'alloc.chunk_ticking.ServerChunkManagerMixin' as rule 'mixin.alloc.chunk_ticking' (added by mods [servercore]) disables it and children
[20:53:41] [main/WARN]: Error loading class: net/minecraft/class_5616 (java.lang.ClassNotFoundException: net/minecraft/class_5616)
[20:53:41] [main/WARN]: @Mixin target net.minecraft.class_5616 was not found registrate-fabric.mixins.json:accessor.BlockEntityRenderersAccessor from mod registrate-fabric
[20:53:46] [main/INFO]: Building unoptimized datafixer
[20:53:49] [main/WARN]: Encountered duplicate API provider registration for item: minecraft:glass_bottle
[20:53:49] [main/WARN]: Encountered duplicate API provider registration for item: minecraft:bucket
[20:53:49] [main/WARN]: Encountered duplicate API provider registration for item: minecraft:bucket
[20:53:49] [main/WARN]: Encountered duplicate API provider registration for item: minecraft:glass_bottle
[20:53:50] [main/WARN]: Encountered duplicate API provider registration for item: minecraft:bucket
[20:53:50] [main/ERROR]: No data fixer registered for immersive_paintings:painting
[20:53:50] [main/ERROR]: No data fixer registered for immersive_paintings:glow_painting
[20:53:50] [main/ERROR]: No data fixer registered for immersive_paintings:graffiti
[20:53:50] [main/ERROR]: No data fixer registered for immersive_paintings:glow_graffiti
[20:53:50] [main/INFO]: Looking for KubeJS plugins...
[20:53:50] [main/INFO]: Found plugin source kubejs
[20:53:50] [main/INFO]: Done in 232.4 ms
[20:53:50] [main/INFO]: Loaded common.properties
[20:53:50] [main/INFO]: Loading Rhino Minecraft remapper...
[20:53:50] [main/INFO]: Rhino properties loaded.
[20:53:50] [main/INFO]: Loading mappings for 1.19.2
[20:53:50] [main/INFO]: Done in 0.055 s
[20:53:51] [main/INFO]: startup_scripts:script.js:3: Hello, World! (You will only see this line once in console, during startup)
[20:53:51] [main/INFO]: Loaded script startup_scripts:script.js in 0.051 s
[20:53:51] [main/INFO]: Loaded 1/1 KubeJS startup scripts in 0.219 s
[20:53:51] [main/INFO]: Registering C2S receiver with id kubejs:send_data_from_client
[20:53:51] [main/INFO]: Registering C2S receiver with id kubejs:first_click
[20:53:51] [main/INFO]: Definitely not up to no good
[20:53:51] [main/INFO]: Giving mobs a fresh coat of paint...
[20:53:51] [main/INFO]: Environment: authHost='https://authserver.mojang.com', accountsHost='https://api.mojang.com', sessionHost='https://sessionserver.mojang.com', servicesHost='https://api.minecraftservices.com', name='PROD'
[20:53:51] [main/INFO]: Found new data pack Fabric Mods, loading it automatically
[20:53:51] [main/INFO]: server_scripts:script.js:3: Hello, World! (You will see this line every time server resources reload)
[20:53:51] [main/INFO]: Loaded script server_scripts:script.js in 0.002 s
[20:53:51] [main/INFO]: Loaded 1/1 KubeJS server scripts in 0.009 s
[20:53:51] [main/INFO]: Scripts loaded
[20:53:51] [main/INFO]: Registered custom recipe handler for type kubejs:shaped
[20:53:51] [main/INFO]: Registered custom recipe handler for type kubejs:shapeless
[20:53:51] [main/INFO]: Registered custom recipe handler for type minecraft:crafting_shaped
[20:53:51] [main/INFO]: Registered custom recipe handler for type minecraft:crafting_shapeless
[20:53:51] [main/INFO]: Registered custom recipe handler for type minecraft:stonecutting
[20:53:51] [main/INFO]: Registered custom recipe handler for type minecraft:smelting
[20:53:51] [main/INFO]: Registered custom recipe handler for type minecraft:blasting
[20:53:51] [main/INFO]: Registered custom recipe handler for type minecraft:smoking
[20:53:51] [main/INFO]: Registered custom recipe handler for type minecraft:campfire_cooking
[20:53:51] [main/INFO]: Registered custom recipe handler for type minecraft:smithing
[20:53:51] [main/INFO]: Scanning recipes...
[20:53:52] [main/INFO]: [fabric-registry-sync] Loaded registry data [file 1/4]
[20:53:53] [main/ERROR]: IngredientDeserializer with ID not found: [farmersdelight:tool] this can be ignored unless issues occur.
[20:53:53] [main/WARN]: Suspicious fluid amount in recipe [sliceanddice:mixing/fertilizer/from_tree_fertilizer]: 500
[20:53:54] [main/INFO]: Loaded dev.properties
[20:53:54] [main/WARN]: Failed to parse recipe 'sliceanddice:mixing/fertilizer/from_phyto[create:mixing]'! Falling back to vanilla: com.google.gson.JsonSyntaxException: Unknown item 'thermal:phytogro'
[20:53:54] [main/WARN]: Failed to parse recipe sliceanddice:mixing/fertilizer/from_phyto[create:mixing]: com.google.gson.JsonSyntaxException: Unknown item 'thermal:phytogro'
[20:53:54] [main/WARN]: Suspicious fluid amount in recipe [farmersdelight:create/filling/chocolate_pie]: 500
[20:53:54] [main/WARN]: Suspicious fluid amount in recipe [farmersdelight:create/mixing/pie_crust_from_mixing]: 250
[20:53:54] [main/WARN]: Suspicious fluid amount in recipe [sliceanddice:mixing/fertilizer/from_compost]: 250
[20:53:54] [main/INFO]: Found 2939 recipes and 0 failed recipes in 134.2 ms
[20:53:54] [main/INFO]: Posted recipe events in 2.318 ms
[20:53:54] [main/WARN]: Suspicious fluid amount in recipe [sliceanddice:mixing/fertilizer/from_tree_fertilizer]: 500
[20:53:54] [main/WARN]: Suspicious fluid amount in recipe [farmersdelight:create/filling/chocolate_pie]: 500
[20:53:54] [main/WARN]: Suspicious fluid amount in recipe [farmersdelight:create/mixing/pie_crust_from_mixing]: 250
[20:53:54] [main/WARN]: Suspicious fluid amount in recipe [sliceanddice:mixing/fertilizer/from_compost]: 250
[20:53:54] [main/INFO]: Modified & removed recipes in 30.21 ms
[20:53:54] [main/INFO]: Added recipes in 1.382 ms
[20:53:54] [main/INFO]: Added 0 recipes, removed 0 recipes, modified 0 recipes, with 0 failed recipes and 0 fall-backed recipes
[20:53:54] [main/INFO]: Injecting recipes
[20:53:54] [main/INFO]: Loaded 2757 advancements
[20:53:55] [main/INFO]: Applied 551 biome modifications to 63 of 63 new biomes in 16.40 ms
[20:53:55] [Server thread/INFO]: Registering compost heaps in village type of plains
[20:53:55] [Server thread/INFO]: Registering compost heaps in village type of savanna
[20:53:55] [Server thread/INFO]: Registering compost heaps in village type of snowy
[20:53:55] [Server thread/INFO]: Registering compost heaps in village type of taiga
[20:53:55] [Server thread/INFO]: Registering compost heaps in village type of desert
[20:53:55] [Server thread/INFO]: Starting background profiler...
[20:53:55] [Server thread/INFO]: The async-profiler engine is not supported for your os/arch (windows10/amd64), so the built-in Java engine will be used instead.
[20:53:56] [Server thread/INFO]: Starting minecraft server version 1.19.2
[20:53:56] [Server thread/INFO]: Loading properties
[20:53:56] [Server thread/INFO]: Default game type: SURVIVAL
[20:53:56] [Server thread/INFO]: Generating keypair
[20:53:56] [Server thread/INFO]: Starting Minecraft server on *:25565
[20:53:56] [Server thread/INFO]: Using default channel type
[20:53:56] [Server thread/INFO]: Preparing level "world"
[20:53:56] [Server thread/INFO]: Preparing start region for dimension minecraft:overworld
[20:54:00] [Worker-Main-8/INFO]: Preparing spawn area: 0%
[20:54:00] [Worker-Main-8/INFO]: Preparing spawn area: 0%
[20:54:00] [Worker-Main-8/INFO]: Preparing spawn area: 0%
[20:54:00] [Worker-Main-8/INFO]: Preparing spawn area: 0%
[20:54:00] [Worker-Main-8/INFO]: Preparing spawn area: 0%
[20:54:00] [Worker-Main-8/INFO]: Preparing spawn area: 0%
[20:54:00] [Worker-Main-8/INFO]: Preparing spawn area: 0%
[20:54:00] [Worker-Main-8/INFO]: Preparing spawn area: 0%
[20:54:00] [Worker-Main-10/INFO]: Preparing spawn area: 58%
[20:54:01] [Server thread/INFO]: Time elapsed: 4255 ms
[20:54:01] [Server thread/INFO]: Done (4.680s)! For help, type "help"
[20:56:07] [User Authenticator #1/INFO]: UUID of player STANN_co is 25bf1851-55d3-4f81-b971-20714d3724c6
[20:56:07] [Server thread/INFO]: STANN_co[/127.0.0.1:55819] logged in with entity id 128 at (2.8156072349993297, 64.0, 25.573628552987245)
[20:56:07] [Netty Server IO #2/ERROR]: Error receiving packet 106
java.lang.NullPointerException: Cannot invoke "net.minecraft.class_2960.toString()" because "$$0" is null
	at net.minecraft.class_2540.method_10812(class_2540.java:638) ~[server-intermediary.jar:?]
	at net.minecraft.class_2788.method_17816(class_2788.java:50) ~[server-intermediary.jar:?]
	at net.minecraft.class_2540.method_34062(class_2540.java:179) ~[server-intermediary.jar:?]
	at net.minecraft.class_2788.method_11052(class_2788.java:27) ~[server-intermediary.jar:?]
	at net.minecraft.class_2545.method_10838(class_2545.java:45) ~[server-intermediary.jar:?]
	at net.minecraft.class_2545.encode(class_2545.java:14) ~[server-intermediary.jar:?]
	at io.netty.handler.codec.MessageToByteEncoder.write(MessageToByteEncoder.java:107) ~[netty-codec-4.1.77.Final.jar:?]
	at io.netty.channel.AbstractChannelHandlerContext.invokeWrite0(AbstractChannelHandlerContext.java:717) ~[netty-transport-4.1.77.Final.jar:?]
	at io.netty.channel.AbstractChannelHandlerContext.invokeWriteAndFlush(AbstractChannelHandlerContext.java:764) ~[netty-transport-4.1.77.Final.jar:?]
	at io.netty.channel.AbstractChannelHandlerContext.write(AbstractChannelHandlerContext.java:790) ~[netty-transport-4.1.77.Final.jar:?]
	at io.netty.channel.AbstractChannelHandlerContext.writeAndFlush(AbstractChannelHandlerContext.java:758) ~[netty-transport-4.1.77.Final.jar:?]
	at io.netty.channel.AbstractChannelHandlerContext.writeAndFlush(AbstractChannelHandlerContext.java:808) ~[netty-transport-4.1.77.Final.jar:?]
	at io.netty.channel.DefaultChannelPipeline.writeAndFlush(DefaultChannelPipeline.java:1025) ~[netty-transport-4.1.77.Final.jar:?]
	at io.netty.channel.AbstractChannel.writeAndFlush(AbstractChannel.java:306) ~[netty-transport-4.1.77.Final.jar:?]
	at net.minecraft.class_2535.method_36942(class_2535.java:209) ~[server-intermediary.jar:?]
	at net.minecraft.class_2535.method_10761(class_2535.java:201) ~[server-intermediary.jar:?]
	at io.netty.util.concurrent.AbstractEventExecutor.runTask(AbstractEventExecutor.java:174) [netty-common-4.1.77.Final.jar:?]
	at io.netty.util.concurrent.AbstractEventExecutor.safeExecute(AbstractEventExecutor.java:167) [netty-common-4.1.77.Final.jar:?]
	at io.netty.util.concurrent.SingleThreadEventExecutor.runAllTasks(SingleThreadEventExecutor.java:470) [netty-common-4.1.77.Final.jar:?]
	at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:503) [netty-transport-4.1.77.Final.jar:?]
	at io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:995) [netty-common-4.1.77.Final.jar:?]
	at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74) [netty-common-4.1.77.Final.jar:?]
	at java.lang.Thread.run(Thread.java:833) [?:?]
[20:56:07] [Netty Server IO #2/ERROR]: Exception occurred in netty pipeline
io.netty.handler.codec.EncoderException: java.lang.NullPointerException: Cannot invoke "net.minecraft.class_2960.toString()" because "$$0" is null
	at io.netty.handler.codec.MessageToByteEncoder.write(MessageToByteEncoder.java:125) ~[netty-codec-4.1.77.Final.jar:?]
	at io.netty.channel.AbstractChannelHandlerContext.invokeWrite0(AbstractChannelHandlerContext.java:717) ~[netty-transport-4.1.77.Final.jar:?]
	at io.netty.channel.AbstractChannelHandlerContext.invokeWriteAndFlush(AbstractChannelHandlerContext.java:764) ~[netty-transport-4.1.77.Final.jar:?]
	at io.netty.channel.AbstractChannelHandlerContext.write(AbstractChannelHandlerContext.java:790) ~[netty-transport-4.1.77.Final.jar:?]
	at io.netty.channel.AbstractChannelHandlerContext.writeAndFlush(AbstractChannelHandlerContext.java:758) ~[netty-transport-4.1.77.Final.jar:?]
	at io.netty.channel.AbstractChannelHandlerContext.writeAndFlush(AbstractChannelHandlerContext.java:808) ~[netty-transport-4.1.77.Final.jar:?]
	at io.netty.channel.DefaultChannelPipeline.writeAndFlush(DefaultChannelPipeline.java:1025) ~[netty-transport-4.1.77.Final.jar:?]
	at io.netty.channel.AbstractChannel.writeAndFlush(AbstractChannel.java:306) ~[netty-transport-4.1.77.Final.jar:?]
	at net.minecraft.class_2535.method_36942(class_2535.java:209) ~[server-intermediary.jar:?]
	at net.minecraft.class_2535.method_10761(class_2535.java:201) ~[server-intermediary.jar:?]
	at io.netty.util.concurrent.AbstractEventExecutor.runTask(AbstractEventExecutor.java:174) [netty-common-4.1.77.Final.jar:?]
	at io.netty.util.concurrent.AbstractEventExecutor.safeExecute(AbstractEventExecutor.java:167) [netty-common-4.1.77.Final.jar:?]
	at io.netty.util.concurrent.SingleThreadEventExecutor.runAllTasks(SingleThreadEventExecutor.java:470) [netty-common-4.1.77.Final.jar:?]
	at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:503) [netty-transport-4.1.77.Final.jar:?]
	at io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:995) [netty-common-4.1.77.Final.jar:?]
	at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74) [netty-common-4.1.77.Final.jar:?]
	at java.lang.Thread.run(Thread.java:833) [?:?]
Caused by: java.lang.NullPointerException: Cannot invoke "net.minecraft.class_2960.toString()" because "$$0" is null
	at net.minecraft.class_2540.method_10812(class_2540.java:638) ~[server-intermediary.jar:?]
	at net.minecraft.class_2788.method_17816(class_2788.java:50) ~[server-intermediary.jar:?]
	at net.minecraft.class_2540.method_34062(class_2540.java:179) ~[server-intermediary.jar:?]
	at net.minecraft.class_2788.method_11052(class_2788.java:27) ~[server-intermediary.jar:?]
	at net.minecraft.class_2545.method_10838(class_2545.java:45) ~[server-intermediary.jar:?]
	at net.minecraft.class_2545.encode(class_2545.java:14) ~[server-intermediary.jar:?]
	at io.netty.handler.codec.MessageToByteEncoder.write(MessageToByteEncoder.java:107) ~[netty-codec-4.1.77.Final.jar:?]
	... 16 more
[20:56:07] [Server thread/INFO]: STANN_co joined the game
[20:56:07] [Server thread/INFO]: STANN_co lost connection: Internal Exception: io.netty.handler.codec.EncoderException: java.lang.NullPointerException: Cannot invoke "net.minecraft.class_2960.toString()" because "$$0" is null
[20:56:07] [Server thread/INFO]: STANN_co left the game
[20:56:07] [Server thread/WARN]: handleDisconnection() called twice
[20:58:19] [Server thread/INFO]: Unknown or incomplete command, see below for error
[20:58:19] [Server thread/INFO]: !!logs<--[HERE]
```

**Comment by PssbleTrngle** [comment] 2023-05-11 09:12
Looks like a duplicate of #55

**Closed as completed by PssbleTrngle** 2023-05-11 09:12 UTC
Labels: bug
