### ISSUE TITLE
Most recent version crashes game during initialization

### ISSUE THREAD

**Issue by FlashOfAsh** [PssbleTrngle/SliceAndDice#168] opened 2024-09-19 19:58 UTC
### What happened?

Nothing happens for a bit as the game tries initializing, stops and crashes after a bit

Provided log info is what seems major after slice and dice was mentioned in latest log

### Loader

fabric

### Mod Version

3.30

### Minecraft Version

1.20

### Relevant log output

```Shell
- sliceanddice 3.3.0
	- smarterfarmers 1.20-2.1.0
	   \-- mixinextras 0.3.6
	- sodium 0.5.11+mc1.20.1
	- squidnoglitch 1.0.2
	- theprinter 1.4.4+1.20
	- trinkets 3.7.2
	- universal-graves 3.0.0+1.20.1
	   |-- common-protection-api 1.0.0
	   |-- fabric-permissions-api-v0 0.2-SNAPSHOT
	   |-- placeholder-api 2.1.3+1.20.1
	   |-- polymer-core 0.5.15+1.20.1
	   |    |-- polymer-networking 0.5.15+1.20.1
	   |    |    \-- polymer-common 0.5.15+1.20.1
	   |    |         \-- packet_tweaker 0.4.0+1.19.4
	   |    \-- polymer-registry-sync-manipulator 0.5.15+1.20.1
	   |-- polymer-resource-pack 0.5.15+1.20.1
	   |    \-- polymer-common 0.5.15+1.20.1
	   |         \-- packet_tweaker 0.4.0+1.19.4
	   |-- polymer-virtual-entity 0.5.15+1.20.1
	   |    \-- polymer-common 0.5.15+1.20.1
	   |         \-- packet_tweaker 0.4.0+1.19.4
	   |-- predicate-api 0.2.1+1.20.1
	   |-- server_translations_api 2.0.0+1.20
	   |    \-- packet_tweaker 0.4.0+1.19.4
	   \-- sgui 1.2.2+1.20
	- universalenchants 8.0.0
	   \-- extensibleenums 7.0.1
	- xaerominimap 24.4.0
	- xaeroworldmap 1.39.0
	- zombieproofdoors 3.4
[13:45:32] [main/INFO]: SpongePowered MIXIN Subsystem Version=0.8.5 Source=file:/C:/Users/Ashton/AppData/Roaming/.minecraft/libraries/net/fabricmc/sponge-mixin/0.12.5+mixin.0.8.5/sponge-mixin-0.12.5+mixin.0.8.5.jar Service=Knot/Fabric Env=CLIENT
[13:45:32] [main/INFO]: Compatibility level set to JAVA_17
[13:45:32] [main/WARN]: Reference map 'codec-config-api-refmap.json' for codec-config-api.mixins.json could not be read. If this is a development environment you can ignore this message
[13:45:32] [main/WARN]: Reference map 'createframed.refmap.json' for createframed.mixins.json could not be read. If this is a development environment you can ignore this message
[13:45:32] [main/INFO]: Loaded configuration file for Lithium: 115 options available, 1 override(s) found
[13:45:32] [main/INFO]: Loaded configuration file for Sodium: 42 options available, 3 override(s) found
[13:45:33] [main/WARN]: Error loading class: io/vram/frex/base/renderer/context/render/EntityBlockRenderContext (java.lang.ClassNotFoundException: io/vram/frex/base/renderer/context/render/EntityBlockRenderContext)
[13:45:33] [main/WARN]: @Mixin target io.vram.frex.base.renderer.context.render.EntityBlockRenderContext was not found porting_lib_base.mixins.json:client.frex.EntityBlockRenderContextMixin from mod porting_lib_base
[13:45:33] [main/WARN]: Error loading class: ca/fxco/moreculling/config/MoreCullingConfig (java.lang.ClassNotFoundException: ca/fxco/moreculling/config/MoreCullingConfig)
[13:45:33] [main/WARN]: Error loading class: com/firemerald/additionalplacements/common/ConfigCommon (java.lang.ClassNotFoundException: com/firemerald/additionalplacements/common/ConfigCommon)
[13:45:33] [main/WARN]: Error loading class: com/firemerald/additionalplacements/block/AdditionalPlacementBlock (java.lang.ClassNotFoundException: com/firemerald/additionalplacements/block/AdditionalPlacementBlock)
[13:45:33] [main/WARN]: @Mixin target com.firemerald.additionalplacements.block.AdditionalPlacementBlock was not found copycats-common.mixins.json:compat.additionalplacements.PlacementBlockMixin from mod copycats
[13:45:33] [main/WARN]: Error loading class: me/jellysquid/mods/lithium/common/ai/pathing/PathNodeDefaults (java.lang.ClassNotFoundException: me/jellysquid/mods/lithium/common/ai/pathing/PathNodeDefaults)
[13:45:33] [main/WARN]: Error loading class: net/kikoz/mcwdoors/objects/JapaneseDoors (java.lang.ClassNotFoundException: net/kikoz/mcwdoors/objects/JapaneseDoors)
[13:45:33] [main/WARN]: @Mixin target net.kikoz.mcwdoors.objects.JapaneseDoors was not found dramaticdoors.mixins.json:fabric.JapaneseDoorBlockMixinFabric from mod dramaticdoors
[13:45:33] [main/WARN]: Error loading class: com/mcwdoors/kikoz/objects/JapaneseDoors (java.lang.ClassNotFoundException: com/mcwdoors/kikoz/objects/JapaneseDoors)
[13:45:33] [main/WARN]: @Mixin target com.mcwdoors.kikoz.objects.JapaneseDoors was not found dramaticdoors.mixins.json:forge.JapaneseDoorBlockMixinForge from mod dramaticdoors
[13:45:33] [main/WARN]: Error loading class: mezz/jei/library/load/PluginCaller (java.lang.ClassNotFoundException: mezz/jei/library/load/PluginCaller)
[13:45:33] [main/WARN]: Force-disabling mixin 'alloc.blockstate.StateMixin' as rule 'mixin.alloc.blockstate' (added by mods [ferritecore]) disables it and children
[13:45:34] [main/WARN]: Mixin 'client.compat.emi_ItemEmiStackMixin' from 'polymer-core' was disabled by EMI (emi). Reason: Please stop mixing into impl. This might cause issues and isn't generally supported!
[13:45:34] [main/WARN]: Error loading class: dev/latvian/mods/kubejs/recipe/RecipesEventJS (java.lang.ClassNotFoundException: dev/latvian/mods/kubejs/recipe/RecipesEventJS)
[13:45:34] [main/WARN]: @Mixin target dev.latvian.mods.kubejs.recipe.RecipesEventJS was not found sliceanddice.mixins.json:RecipeEventJSMixin from mod sliceanddice
[13:45:34] [main/WARN]: Force-disabling mixin 'features.render.entity.CuboidMixin' as rule 'mixin.features.render.entity' (added by mods [iris]) disables it and children
[13:45:34] [main/WARN]: Force-disabling mixin 'features.render.entity.ModelPartMixin' as rule 'mixin.features.render.entity' (added by mods [iris]) disables it and children
[13:45:34] [main/WARN]: Force-disabling mixin 'features.render.entity.cull.EntityRendererMixin' as rule 'mixin.features.render.entity' (added by mods [iris]) disables it and children
[13:45:34] [main/WARN]: Force-disabling mixin 'features.render.entity.shadows.EntityRenderDispatcherMixin' as rule 'mixin.features.render.entity' (added by mods [iris]) disables it and children
[13:45:34] [main/WARN]: Force-disabling mixin 'features.render.gui.font.GlyphRendererMixin' as rule 'mixin.features.render.gui.font' (added by mods [iris]) disables it and children
[13:45:34] [main/WARN]: Force-disabling mixin 'features.render.world.sky.BackgroundRendererMixin' as rule 'mixin.features.render.world.sky' (added by mods [iris]) disables it and children
[13:45:34] [main/WARN]: Force-disabling mixin 'features.render.world.sky.ClientWorldMixin' as rule 'mixin.features.render.world.sky' (added by mods [iris]) disables it and children
[13:45:34] [main/WARN]: Force-disabling mixin 'features.render.world.sky.WorldRendererMixin' as rule 'mixin.features.render.world.sky' (added by mods [iris]) disables it and children
[13:45:34] [main/WARN]: Error loading class: com/firemerald/additionalplacements/block/AdditionalPlacementBlock (java.lang.ClassNotFoundException: com/firemerald/additionalplacements/block/AdditionalPlacementBlock)
[13:45:34] [main/WARN]: Error loading class: com/firemerald/additionalplacements/block/AdditionalPlacementBlock (java.lang.ClassNotFoundException: com/firemerald/additionalplacements/block/AdditionalPlacementBlock)
```

**Comment by Poopooracoocoo** [comment] 2024-09-20 23:41
Got a crash report?

**Comment by FlashOfAsh** [comment] 2024-09-21 01:55
I infact do have a crash report
[crash-2024-09-19_13.45.52-client.txt](https://github.com/user-attachments/files/17082423/crash-2024-09-19_13.45.52-client.txt)

**Comment by PssbleTrngle** [comment] 2024-09-21 09:05
Looks like its a duplicate of #169, although on fabric on not quilt. Still not sure why that happens

**Closed as not planned by PssbleTrngle** 2024-09-21 09:05 UTC
Labels: bug

**Comment by FlashOfAsh** [comment] 2024-09-21 17:18
you say it's a duplicate of it but i think it's still good info, since now we are aware that something may just be dead wrong on the fabric side of things generally

**Comment by JupiterSky11** [comment] 2024-09-21 20:31
Can reproduce.
MC version 1.20.1, Create version v0.5.1.f Patch 1, Fabric version 0.16.5.
Can provide logs if needed.  Fails at recipe injection.

**Comment by PssbleTrngle** [comment] 2024-09-21 21:22
Yes definitely helpful and good info. Don't get me wrong, I'm grateful you opened an issue as well, I just closed it to keep all the info all in one thread to have a better overview, since I think it's probably caused by the same problem

**Comment by FlashOfAsh** [comment] 2024-09-21 22:10
that is fair, and while I don't have much coding experience, with quilt and fabric being similar enough for such a weird issue to occur it's probably something baseline, maybe just some entirely random spelling error
